### ISSUE TITLE
New API features

### ISSUE THREAD

**Issue by peterdebruijn** [Kevin-Bronsdijk/SeaMist#3]
Hi Kevin,

Kraken.IO reased new features in their API. The thing i like most is the ability to set metatags for Amazone and Azure. Can you add this functionality or do you need help with this?

Peter

**Comment by Kevin-Bronsdijk** [comment]
Seems like a fairly legit request, will look at this today.

**Comment by Kevin-Bronsdijk** [comment]
I have just committed the source code required for release 1.1.6 (also available on nuget)

ps: The docs will be updated later but sample coded can be found in tests:

_KrakenClient_OptimizeWaitAzureAddHeadersAndMeta_IsTrue
KrakenClient_OptimizeWaitAmazonAddHeadersAndMeta_IsTrue_

Had to upgrade Newtonsoft.Json to version 8.0.3 because of casing issues when serializing dictionaries...

---

var dataStore = new SeaMist.Model.S3.DataStore(
                Settings.AmazonKey,
                Settings.AmazonSecret,
                Settings.AmazonBucket,
                string.Empty
                );

dataStore.AddMetadata("test1", "value11"); 
dataStore.AddMetadata("test2", "value22"); 
 dataStore.AddHeaders("Cache-Control", "max-age=2222"); 

var response = krakenClient.OptimizeWait(
new SeaMist.Model.S3.OptimizeWaitRequest(
new Uri(TestData.ImageOne),
dataStore));
