### ISSUE TITLE
Generating multiple sizes from a single input image

### ISSUE THREAD

**Issue by MarkFl12** [Kevin-Bronsdijk/SeaMist#4]
Please could you update the library to support this feature.

Details of this can be found in Kraken.io's documentation here:
https://kraken.io/docs/generating-image-sets

**Comment by Kevin-Bronsdijk** [comment]
Hi, could you let me know what you are looking from this feature?  Is it syntactical or would you like to reduce the total amount of calls? 

I recently covered why I haven’t implemented Image Sets within a recent SeaMist blog post (included the details at the end of this comment).  However, I’m thinking of creating a batch wrapper which would be responsible for executing all calls a sync behind the scenes. 

pseudo code: 
`
List<itemId> Optimize (List<UrlToOptimize>,  List<OptimizeInstruction>)
`

Statement from the SeaMist blogost:
Image Sets – I won’t implement image sets because i don’t like the way kraken.io designed this feature. What I would like see this implemented as multipart content instead, the same as for example WEB API.

**Comment by MarkFl12** [comment]
I'd like to be able to upload a file once, and receive several different re-sizes of that image back. If the original image is quite large, uploading it multiple times can be quite slow.

**Comment by Kevin-Bronsdijk** [comment]
Makes sense. I wasn’t aware that it’s possible to use Direct Upload in conjunction with Image Sets. I will have to plan when this can be implemented (most likely this weekend)

Also moving the SeaMist repository to kraken-net soon and you therefore might be required to upgrade from SeaMist to the kraken-net (optimized version of SeaMist)

**Comment by Kevin-Bronsdijk** [comment]
Just realeased version 1.1.8 on Nuget. This release includes Image Sets but without the support for external storage and overriding parameters. 

Samples can be found within the bottom bart of _IntergrationTest.cs_

Added support for:
-  Wait + Upload
-  Wait + External URL
-  Callback + Upload
-  Callback + External URL

**Simple Sample => Wait + Upload**

```
 var request = new OptimizeSetUploadWaitRequest();
            request .AddSet(new SetResizeImage { Name = "test1", Height = 10, Width = 10 });
            request .AddSet(new SetResizeImage { Name = "test2", Height = 15, Width = 15 });
            request .AddSet(new SetResizeImage { Name = "test3", Height = 20, Width = 20 });

            var response = krakenClient.OptimizeWait("c:\bla.png",
                request
                );

            var result = response.Result;

            foreach (var item in result.Body.Results)
            {
                item.KrakedUrl
            }
```
